// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEPLACEME_WEB',
    appId: '1:114043642506:web:0dbcdf8cb0afbdf4d84373',
    messagingSenderId: '114043642506',
    projectId: 'duaab89-67c12',
    authDomain: 'duaab89-67c12.firebaseapp.com',
    storageBucket: 'duaab89-67c12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARyyucFxB5h22FyZM9SRIfISYAIzbcKM0',
    appId: '1:114043642506:android:9799d6564776feb7d84373',
    messagingSenderId: '114043642506',
    projectId: 'duaab89-67c12',
    storageBucket: 'duaab89-67c12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEPLACEME_IOS',
    appId: '1:114043642506:ios:PLACEHOLDER',
    messagingSenderId: '114043642506',
    projectId: 'duaab89-67c12',
    storageBucket: 'duaab89-67c12.firebasestorage.app',
    iosBundleId: 'com.example.duAlumniFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEPLACEME_MACOS',
    appId: '1:114043642506:ios:PLACEHOLDER',
    messagingSenderId: '114043642506',
    projectId: 'duaab89-67c12',
    storageBucket: 'duaab89-67c12.firebasestorage.app',
    iosBundleId: 'com.example.duAlumniFlutter',
  );
}
